version: '3.8'

services:
  net-ops:
    container_name: netops-offline
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "5100:5100"       # Web UI
      - "514:514/udp"     # Syslog Listener
    env_file:
      - ../.env
    environment:
      - DATA_PATH=/app/data
      - IS_DOCKER=True
    volumes:
      - ../data:/app/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  netops_data: